buy_me_a_coffee: theelderemo
ko_fi: theelderemo
thanks_dev: theelderemo
custom: [https://www.paypal.com/us/fundraiser/charity/3712024, https://giving.hireheroesusa.org/give/154895/#!/donation/checkout]
